# Generated by Django 5.2.1 on 2025-06-19 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0059_merge_20250618_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount collected in this transaction', max_digits=12)),
                ('collection_date', models.DateField(default=django.utils.timezone.now, help_text='Date the collection was made')),
                ('collection_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque'), ('online_payment', 'Online Payment')], default='cash', help_text='Mode of payment', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partially_collected', 'Partially Collected'), ('failed', 'Failed')], default='completed', help_text='Status of the collection', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for the payment (e.g., transaction ID)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='The invoice this collection applies to', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='company.invoice')),
            ],
        ),
    ]
