# Generated by Django 5.2.1 on 2025-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Name of the account holder for bank transfer or cheque', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number for bank transfer or cheque', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Date on the cheque', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number for cheque payments', max_length=100, null=True),
        ),
    ]
