# Generated by Django 5.2.1 on 2025-06-25 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_alter_additionalcharge_status_alter_invoice_status_and_more'),
        ('finance', '0003_collection_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('deposit', 'Deposit Refund'), ('excess', 'Excess Payment Refund'), ('other', 'Other Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit_note', 'Credit Note')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('processed_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.invoice')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.users')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='company.tenancy')),
            ],
        ),
    ]
