# Generated by Django 5.2.1 on 2025-07-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_alter_additionalcharge_status_alter_invoice_status_and_more'),
        ('finance', '0004_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('refunded', 'Refunded'), ('adjusted', 'Adjusted')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overpayment', to='finance.collection')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overpayments', to='company.invoice')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overpayments', to='company.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.additionalcharge')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='finance.collection')),
                ('payment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.paymentschedule')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('payment_schedule__isnull', False), ('additional_charge__isnull', False), _connector='OR'), name='either_payment_schedule_or_additional_charge')],
            },
        ),
    ]
