# Generated by Django 5.2.1 on 2025-08-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
        ('company', '0060_alter_additionalcharge_status_alter_invoice_status_and_more'),
        ('finance', '0005_overpayment_paymentdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_comp', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_user', to='company.users'),
        ),
        migrations.AddField(
            model_name='refund',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_comp', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_user', to='company.users'),
        ),
    ]
