# Generated by Django 5.2.1 on 2025-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_no1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_no2', models.CharField(blank=True, max_length=15, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_photos/')),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
