# Generated by Django 5.2.1 on 2025-05-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('building_no', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('land_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('building_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_comp', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('License', 'License'), ('Certificate', 'Certificate'), ('Permit', 'Permit')], max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='document_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_comp', to='company.building')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('no_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('no_of_bathrooms', models.IntegerField(blank=True, null=True)),
                ('premise_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_status', models.CharField(choices=[('inactive', 'inactive'), ('pending', 'pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_building', to='company.building')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_comp', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('License', 'License'), ('Certificate', 'Certificate'), ('Permit', 'Permit')], max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='document_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_comp', to='company.units')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_type_comp', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='units',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_typ_comp', to='company.unittype'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='user_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Sales', 'Sales')], max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comp', to='accounts.company')),
            ],
        ),
    ]
