# Generated by Django 5.2.1 on 2025-05-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_status'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mas_type_comp', to='accounts.company')),
            ],
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ams_comp', to='company.masterdocumenttype'),
        ),
        migrations.AlterField(
            model_name='unitdocumenttype',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ams_doc_comp', to='company.masterdocumenttype'),
        ),
    ]
