# Generated by Django 5.2.1 on 2025-05-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_tenant_tenantdocumenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='building_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='building_name',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='building_no',
            new_name='license_no',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='plot_no',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='land_mark',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tenant',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_comp', to='company.idtype'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sponser_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sponser_id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponser_id_comp', to='company.idtype'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sponser_id_validity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sponser_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Blacklist', 'Blacklist')], default='active', max_length=20),
        ),
    ]
