# Generated by Django 5.2.1 on 2025-05-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_building_user_chargecode_user_charges_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sales', 'Sales'), ('Store', 'Store')], max_length=255, null=True),
        ),
    ]
