# Generated by Django 5.2.1 on 2025-05-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_users_email_alter_users_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
