# Generated by Django 5.2.1 on 2025-05-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_tenancy_paymentschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='vat',
        ),
    ]
