# Generated by Django 5.2.1 on 2025-05-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_status'),
        ('company', '0014_remove_paymentschedule_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnn_comp', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnnt', to='company.users'),
        ),
    ]
