# Generated by Django 5.2.1 on 2025-05-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_paymentschedule_vat_tenancy_company_tenancy_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='deposite',
            new_name='deposit',
        ),
    ]
