# Generated by Django 5.2.1 on 2025-05-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_additionalcharges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalCharges',
        ),
    ]
