# Generated by Django 5.2.1 on 2025-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_delete_additionalcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('occupied', 'Occupied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
