# Generated by Django 5.2.1 on 2025-05-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_tenancy_status_alter_paymentschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='is_termination',
            field=models.BooleanField(default=False),
        ),
    ]
