# Generated by Django 5.2.1 on 2025-05-26 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_tenancy_is_close_tenancy_is_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='previous_tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_tenancies', to='company.tenancy'),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='tenancy_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
