# Generated by Django 5.2.1 on 2025-05-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_tenancy_previous_tenancy_tenancy_tenancy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
