# Generated by Django 5.2.1 on 2025-05-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_alter_tenancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='is_reniew',
            field=models.BooleanField(default=False),
        ),
    ]
