# Generated by Django 5.2.1 on 2025-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_tenancy_is_reniew'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
