# Generated by Django 5.2.1 on 2025-05-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_units_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='Building',
            new_name='building',
        ),
    ]
