# Generated by Django 5.2.1 on 2025-05-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_rename_building_documenttype_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='charge_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_code_comp', to='company.chargecode'),
        ),
    ]
