# Generated by Django 5.2.1 on 2025-05-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
        ('company', '0029_alter_building_status_alter_units_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings_country', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='building',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings_state', to='accounts.state'),
        ),
    ]
