# Generated by Django 5.2.1 on 2025-05-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_alter_building_status_alter_units_unit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField()),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.charges')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='company.tenancy')),
            ],
        ),
    ]
