# Generated by Django 5.2.1 on 2025-05-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_additionalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='additionalcharge',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='additionalcharge',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='charge_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chvcar', to='company.charges'),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tedffnanc', to='company.tenancy'),
        ),
    ]
