# Generated by Django 5.2.1 on 2025-05-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_additionalcharge_status_additionalcharge_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='company.tenancy'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='company.tenancy'),
        ),
    ]
