# Generated by Django 5.2.1 on 2025-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_alter_paymentschedule_tenancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
