# Generated by Django 5.2.1 on 2025-05-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_alter_additionalcharge_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated'), ('closed', 'Closed'), ('renewed', 'Renewed')], default='pending', max_length=20),
        ),
    ]
