# Generated by Django 5.2.1 on 2025-06-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_building_country_building_state'),
        ('company', '0035_alter_tenancy_status'),
    ]

    operations = [
    ]
