# Generated by Django 5.2.1 on 2025-06-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
        ('company', '0036_merge_20250602_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(max_length=100, unique=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicable_from', models.DateField(blank=True, null=True)),
                ('applicable_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_taxes', to='accounts.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='accounts.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='accounts.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_taxes', to='company.users')),
            ],
        ),
    ]
