# Generated by Django 5.2.1 on 2025-06-03 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
        ('company', '0037_taxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='taxes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes_c', to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes_state', to='accounts.state'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='tax_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='taxes',
            constraint=models.UniqueConstraint(condition=models.Q(('applicable_to__isnull', True), ('is_active', True)), fields=('company', 'tax_type'), name='unique_active_tax_per_company'),
        ),
    ]
