# Generated by Django 5.2.1 on 2025-06-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
        ('company', '0038_alter_taxes_options_taxes_created_at_taxes_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='taxes',
            field=models.ManyToManyField(blank=True, null=True, related_name='charges_taxes', to='company.taxes'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes_country', to='accounts.country'),
        ),
    ]
