# Generated by Django 5.2.1 on 2025-06-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_alter_taxes_options_taxes_created_at_taxes_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdocumenttype',
            name='expiry_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='issue_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='upload_file',
            field=models.BooleanField(default=False),
        ),
    ]
