# Generated by Django 5.2.1 on 2025-06-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_state'),
        ('company', '0039_charges_taxes_alter_taxes_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='taxes',
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='expiry_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='issue_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterdocumenttype',
            name='upload_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='country',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='taxes_c', to='accounts.country'),
            preserve_default=False,
        ),
    ]
