# Generated by Django 5.2.1 on 2025-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_charges_taxes_alter_taxes_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
