# Generated by Django 5.2.1 on 2025-06-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_paymentschedule_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcharge',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
