# Generated by Django 5.2.1 on 2025-06-06 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_remove_charges_taxes_masterdocumenttype_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_tenants', to='company.masterdocumenttype'),
        ),
    ]
