# Generated by Django 5.2.1 on 2025-06-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_alter_tenantdocumenttype_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.tenant'),
        ),
    ]
