# Generated by Django 5.2.1 on 2025-06-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_additionalcharge_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='commision',
            new_name='commission',
        ),
    ]
