# Generated by Django 5.2.1 on 2025-06-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_alter_tenant_status_alter_tenantdocumenttype_tenant'),
        ('company', '0042_rename_commision_tenancy_commission'),
    ]

    operations = [
    ]
