# Generated by Django 5.2.1 on 2025-06-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_alter_tenant_status_alter_tenantdocumenttype_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_comp', to='company.masterdocumenttype'),
        ),
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_comp', to='company.tenant'),
        ),
    ]
