# Generated by Django 5.2.1 on 2025-06-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_alter_tenant_status_and_more'),
        ('company', '0043_merge_20250610_1353'),
    ]

    operations = [
    ]
