# Generated by Django 5.2.1 on 2025-06-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_merge_20250610_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='charges_taxes', to='company.taxes'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_comp', to='company.masterdocumenttype'),
        ),
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_comp', to='company.tenant'),
        ),
    ]
