# Generated by Django 5.2.1 on 2025-06-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_alter_tenantdocumenttype_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_comp', to='company.masterdocumenttype'),
        ),
        migrations.AlterField(
            model_name='tenantdocumenttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_comp', to='company.tenant'),
        ),
    ]
