# Generated by Django 5.2.1 on 2025-06-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_charges_taxes_alter_tenant_status_and_more'),
        ('company', '0044_merge_20250610_0848'),
    ]

    operations = [
    ]
