# Generated by Django 5.2.1 on 2025-06-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_alter_tenantdocumenttype_doc_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='commision',
            new_name='commission',
        ),
        migrations.AddField(
            model_name='additionalcharge',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='charges',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='charges_taxes', to='company.taxes'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
