# Generated by Django 5.2.1 on 2025-06-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_invoice_company_invoice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('additional_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='company.additionalcharge')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='company.invoice')),
                ('payment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='company.paymentschedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('payment_schedule__isnull', False)), fields=('payment_schedule',), name='unique_payment_schedule_invoice'), models.UniqueConstraint(condition=models.Q(('additional_charge__isnull', False)), fields=('additional_charge',), name='unique_additional_charge_invoice')],
            },
        ),
    ]
