# Generated by Django 5.2.1 on 2025-06-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_invoiceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
