# Generated by Django 5.2.1 on 2025-06-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_merge_20250611_0907'),
        ('company', '0049_delete_invoiceitem'),
    ]

    operations = [
    ]
