# Generated by Django 5.2.1 on 2025-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_delete_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_charges',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='company.additionalcharge'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_schedules',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='company.paymentschedule'),
        ),
    ]
