# Generated by Django 5.2.1 on 2025-06-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0050_invoice_additional_charges_invoice_payment_schedules'),
        ('company', '0050_merge_20250613_1018'),
    ]

    operations = [
    ]
