# Generated by Django 5.2.1 on 2025-06-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0050_invoice_additional_charges_invoice_payment_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcharge',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
