# Generated by Django 5.2.1 on 2025-06-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_additionalcharge_in_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_due', models.PositiveIntegerField(default=7, help_text='Number of days before due date to generate and send invoice')),
                ('combine_charges', models.BooleanField(default=False, help_text='If True, combine PaymentSchedule and AdditionalCharge in one invoice. If False, send separate invoices.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_configs', to='company.tenancy')),
            ],
            options={
                'unique_together': {('tenancy',)},
            },
        ),
    ]
