# Generated by Django 5.2.1 on 2025-06-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_additionalcharge_in_date'),
        ('company', '0051_merge_20250613_1036'),
    ]

    operations = [
    ]
