# Generated by Django 5.2.1 on 2025-06-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_invoiceautomationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='Indicates if this invoice was generated automatically'),
        ),
    ]
