# Generated by Django 5.2.1 on 2025-06-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_merge_20250616_0910'),
        ('company', '0053_invoice_is_automated'),
    ]

    operations = [
    ]
