# Generated by Django 5.2.1 on 2025-06-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0055_alter_additionalcharge_status_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total of all charges before payments', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('invoice', 'Invoice')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total payment amount for this invoice', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('invoice', 'Invoice')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.additionalcharge')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='company.invoice')),
                ('payment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.paymentschedule')),
            ],
            options={
                'unique_together': {('invoice', 'additional_charge'), ('invoice', 'payment_schedule')},
            },
        ),
    ]
