# Generated by Django 5.2.1 on 2025-06-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0054_merge_20250617_1104'),
        ('company', '0055_alter_additionalcharge_status_alter_invoice_status_and_more'),
    ]

    operations = [
    ]
