# Generated by Django 5.2.1 on 2025-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0056_invoice_gross_amount_alter_additionalcharge_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gross_amount',
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoice', 'Invoice')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoice', 'Invoice')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='InvoicePayment',
        ),
    ]
