# Generated by Django 5.2.1 on 2025-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_remove_invoice_gross_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcharge',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='additionalcharge',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='paid_amount',
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('invoice', 'Invoice')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('invoice', 'Invoice')], default='pending', max_length=20),
        ),
    ]
