# Generated by Django 5.2.1 on 2025-06-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0056_merge_20250618_0856'),
        ('company', '0058_remove_additionalcharge_balance_and_more'),
    ]

    operations = [
    ]
