# Generated by Django 5.2.1 on 2025-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_alter_additionalcharge_status_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated'), ('closed', 'Closed'), ('renewed', 'Renewed'), ('vacant', 'Vacant')], default='pending', max_length=20),
        ),
    ]
