# Generated by Django 5.2.1 on 2025-06-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_exp', to='company.tenancy'),
        ),
    ]
