# Generated by Django 5.2.1 on 2025-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0061_expense_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
