# Generated by Django 5.2.1 on 2025-06-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_expense_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
